import { jsPDF } from 'jspdf';

export function generateSuccessCertificate(caseId, passphrase) {
    const doc = new jsPDF();

    // Font config
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(13, 17, 23); // bg-primary (dark)

    // Title
    doc.text("SAFEVOICE CONFIDENTIAL RECORD", 20, 30);

    // Date
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 40);

    // Case ID Box
    doc.setDrawColor(55, 65, 81); // border-default
    doc.setFillColor(249, 250, 251); // text-primary (light)
    doc.rect(20, 50, 170, 30, 'FD');

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("YOUR CASE ID", 25, 60);

    doc.setFont("courier", "bold"); // monospace
    doc.setFontSize(18);
    doc.text(caseId, 25, 72);

    // Passphrase Box
    doc.setFillColor(254, 243, 199); // warning yellowish background
    doc.rect(20, 90, 170, 60, 'FD');

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("YOUR SECRET PASSPHRASE (DO NOT SHARE)", 25, 100);

    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.text("This 12-word phrase is your private key. SafeVoice does not store it.", 25, 110);
    doc.text("If you lose it, you lose access to track your complaint.", 25, 115);

    doc.setFont("courier", "bold");
    doc.setFontSize(16);

    // Format passphrase nicely into 3 lines
    const words = passphrase.split(' ');
    const line1 = words.slice(0, 4).join(' ');
    const line2 = words.slice(4, 8).join(' ');
    const line3 = words.slice(8, 12).join(' ');

    doc.text(line1, 25, 130);
    doc.text(line2, 25, 138);
    doc.text(line3, 25, 146);

    // Next steps
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("WHAT HAPPENS NEXT:", 20, 170);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    const steps = [
        "1. Your complaint has been anonymously submitted to the ICC.",
        "2. The ICC has 7 days to acknowledge receipt of this complaint.",
        "3. Check your status regularly at safevoice.org/track using your passphrase.",
        "4. Under POSH Act, the ICC inquiry must complete within 90 days."
    ];

    let y = 180;
    steps.forEach(step => {
        doc.text(step, 20, y);
        y += 10;
    });

    // Disclaimer
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(107, 114, 128); // text-muted
    doc.text("This document is auto-generated by SafeVoice cryptographic protocol.", 20, Math.min(y + 20, 280));
    doc.text("Keep it secure. Print it or store it offline.", 20, Math.min(y + 25, 285));

    // Save the PDF
    doc.save(`SafeVoice-Case-${caseId}.pdf`);
}

export function generateEvidenceCertificate(fileHash, filename, caseId, date) {
    const doc = new jsPDF();

    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(13, 17, 23);
    doc.text("EVIDENCE DEPOSIT CERTIFICATE", 20, 30);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Certificate Generated: ${new Date().toLocaleString()}`, 20, 40);

    doc.setLineWidth(0.5);
    doc.line(20, 45, 190, 45);

    doc.setFontSize(12);
    doc.text("This document certifies that the following digital evidence was securely", 20, 60);
    doc.text(`deposited and cryptographically hashed for Case ID: `, 20, 67);
    doc.setFont("helvetica", "bold");
    doc.text(caseId, 115, 67);

    doc.setDrawColor(55, 65, 81);
    doc.setFillColor(249, 250, 251);
    doc.rect(20, 80, 170, 70, 'FD');

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("FILE DETAILS", 25, 90);

    doc.setFont("helvetica", "normal");
    doc.text(`Original Filename:  ${filename}`, 25, 105);
    doc.text(`Deposit Timestamp:  ${new Date(date).toUTCString()}`, 25, 115);

    doc.setFont("helvetica", "bold");
    doc.text("CRYPTOGRAPHIC FINGERPRINT (SHA-256):", 25, 130);

    doc.setFont("courier", "bold");
    doc.setFontSize(10);

    // Format long hash
    const hashPart1 = fileHash.substring(0, 32);
    const hashPart2 = fileHash.substring(32);
    doc.text(hashPart1, 25, 138);
    doc.text(hashPart2, 25, 144);

    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.text("This hash guarantees that the file has not been altered since the deposit date.", 20, 170);
    doc.text("It provides non-repudiation and stands as immutable evidence in POSH proceedings.", 20, 176);

    doc.save(`Evidence-Cert-${filename}.pdf`);
}
